#spring.application.name=seaport
server:
  port: 8088
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": category:com.project.seaport.models.Category
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

