#spring.application.name=demo
#server.port=8088
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#api.prefix=api/v1

#ddl-auto: none   //tao table thu cong trong workbernch, k dung tu dong bang spring
#driver-class-name: org.mariadb.jdbc.Driver

#dialect: ngon ngu giao tiep sql cua Hibernate
server:
    port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webcang?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibenate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1
jwt:
  expiration: 2592000
    #30 days=30*24*60*60=
  secretKey: QE5kl4B4CZxfBao2qYRLzewKirzzcgISNaNxs55Pvfk=